### PR TITLE
Fix/refactor team section component

### PR DESCRIPTION
**Pull request by oladhari**
updated TeamSection, refactoring code little bit to avoid repetition `DRY`

### CODE REVIEW

**Comment by Farid212** [comment]
could you please put back "Dai" please?

**Comment by oladhari** [comment]
> could you please put back "Dai" please?

sure

**Comment by oladhari** [comment]
Screenshot from 2019-07-25 18-53-49
@Farid212 is it ok like this?

**Comment by Farid212** [comment]
great one

**Comment by Farid212** [comment]
you need to register to 
https://circleci.com/signup/
or test won't apply to your code

could you please proceed to registration?

**Comment by oladhari** [comment]
> you need to register to
> https://circleci.com/signup/
> or test won't apply to your code
> 
> could you please proceed to registration?

I just registered but have no idea how I should enable it for asmuch

**Comment by Farid212** [comment]
you dont, you already in since you are part of the project

**Pull request merged**
